### ISSUE TITLE
changing physical layout to support `go install`

### ISSUE THREAD

**Issue by nikolaydubina** [zarldev/goenums#12]
no it is impossible to install via `go install`.

recommend changing physical layout to make it possible. that would greatly help adoption.

option A) move to /cmd/goenums/goenums.go and keep main module a "library module"
option B) move to /goenums.go and make whole module a "main module"

I recommend option B).

**Comment by Hidayathamir** [comment]
For option B, I believe to install goenums it will use this command.

```shell
go install github.com/zarldev/goenums
```

How option A would look like when installing?

**Comment by zarldev** [comment]
Thanks, done and implemented. Added to README.md
