### ISSUE TITLE
Camelcase naming

### ISSUE THREAD

**Issue by matdurand** [zarldev/goenums#21]
Hi

Is it possible to support camel casing of the enum name?

For example
```
type discountType int

//go:generate goenums models.go
const (
	unknown discountType = iota // invalid
	percentage
)
```
produce code that doesn't compile.

For example, it outputs this
```
func (i discounttype) String() string {
	if i < 0 || i >= discounttype(len(_discounttype_index)-1) {
		return "discounttype(" + (strconv.FormatInt(int64(i), 10) + ")")
	}
	return _discounttype_name[_discounttype_index[i]:_discounttype_index[i+1]]
}
```
but `discounttype` is wrong as it should be `discountType`.

And also, it ignores the camel case completely when generating the enum struct
```
type Discounttype struct {
	discountType
}
```

Happy to create a PR if you agree that this should be supported.
Thanks

**Comment by zarldev** [comment]
Hey @matdurand thanks for this - I actually also encountered this recently.  I have pushed an update (v0.2.5) which should now correctly handle this use case.

**Comment by zarldev** [comment]
> I don't mind the private `discounttypeContainer`, but I think `Discounttypes` should be `DiscountTypes`

I fully agree - will be fixed in v.0.2.6 - with some other fixes.

**Comment by matdurand** [comment]
Works like a charm. Thanks!
