### ISSUE TITLE
Ask your TODO, "stringer cmd tool"

### ISSUE THREAD

**Issue by Hidayathamir** [zarldev/goenums#3]
Can you explain what do you mean by "**Make use of stringer cmd tool for string representation**" in your [TODO](https://github.com/zarldev/goenums?tab=readme-ov-file#todo)?

Is it like [this](https://github.com/zarldev/goenums/pull/2/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R160).

```shell
goenums -help
```

```shell
Usage of goenums:
  -cfg string
        Config file path. E.g -cfg "./input.json"
  -output string
        Output path that will be generated. E.g -output "./output"
  -package string
        Package enum that will be generated. E.g -package "validation"
  -type string
        Enum type. E.g -type "status"
  -values string
        Enum values seperated by ",". E.g -values "Failed, Passed, Skipped, Scheduled, Running"
```

**Comment by zarldev** [comment]
See latest string method - from the https://pkg.go.dev/golang.org/x/tools/cmd/stringer tool
