### ISSUE TITLE
removing exported Parse 

### ISSUE THREAD

**Issue by nikolaydubina** [zarldev/goenums#6]
why we need Parse? can we avoid generating it? can at least make it optional?

my problem with it, as it encourages reflection and runtime dynamic typing.

if you compiled code already, how come some symbols still need type detection at runtime?

(marshalling is already covered in different methods).

**Comment by zarldev** [comment]
What if the enum bytes are from another source, re: a message , you can implement the required interface and Parse. Ill be leaving it Exported.
