### ISSUE TITLE
add "generated" header to the top of generated file

### ISSUE THREAD

**Issue by nikolaydubina** [zarldev/goenums#9]
this is useful to skip code coverage (if you don't generate tests yet). generally good to mark files as generated.

here is example of how to detect generated files. ideally you would need to use some functions from ast standard package.

https://github.com/nikolaydubina/go-instrument/blob/0f8e3b6b8194cd3a750046f20991d2af46e2caea/main.go#L52C25-L52C43

**Comment by zarldev** [comment]
Added. Thanks!
